# Simple workflow for deploying static content to GitHub Pages
name: Publish Docker image

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# env
env:
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE_NAME_BLOG: dbopen/my-blog 
  
# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  crawl_page:
    name: Crawl Blog Page
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      # Install pip and scrapy
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scrapy
      - name: Crawl
        run: scrapy crawl blog && ll .
